CREATE TABLE MEMBER(
   MID VARCHAR(10) PRIMARY KEY,
   MPW VARCHAR(10) NOT NULL,
   MNAME VARCHAR(20) NOT NULL
);

CREATE TABLE BOARD(
   BID INT PRIMARY KEY,
   MID VARCHAR(10) NOT NULL, 
   MSG VARCHAR(50) NOT NULL,
   FAVCNT INT DEFAULT 0,
   RCNT INT DEFAULT 0
);
-- FK는 반드시 상대 테이블의 PK를 사용

CREATE TABLE REPLY(
   RID INT PRIMARY KEY,
   MID VARCHAR(10) NOT NULL,
   BID INT NOT NULL,
   RMSG VARCHAR(30) NOT NULL,
   CONSTRAINT BOARD_REPLY FOREIGN KEY (BID) REFERENCES BOARD (BID) ON DELETE CASCADE
);
-- BIARD_REPLY 제약조건의 명칭 
--CASCADE : 따라서 삭제 할거야 

SELECT * FROM USER_TABLES

DROP TABLE MEMBER;
DROP TABLE BOARD;
DROP TABLE REPLY;

SELECT * FROM MEMBER;
SELECT * FROM (SELECT A.*,ROWNUM AS RNUM FROM (SELECT * FROM MEMBER ORDER BY MID DESC) A WHERE ROWNUM<=3) WHERE RNUM>=1;
SELECT * FROM BOARD WHERE MID = 'sudal' AND ROWNUM <= 3 ORDER BY BID DESC;
